device: 'cpu'

seed: False

data:
    path: './data/'

model:
    name: 'gmm'
    path: './cache/'
    n_clusters: 4

optimizer:
    name: 'adam'
    epochs: 10
    params:
        lr: 0.001
        regularization: 0.0001